# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_link', '0009_link_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='classes',
            field=models.CharField(blank=True, help_text='A list of class names separated by spaces for styling purposes', max_length=500, verbose_name='anchor'),
        ),
    ]
